[package]
name = "wiremock_checkpoint"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
googletest = { workspace = true }
tokio = { workspace = true }
wiremock = { workspace = true }
