[package]
name = "tempfile_tempdir"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-manifest = "0.12.1"
cargo-util-schemas = "0.1.0"
toml = "0.8.8"

[dev-dependencies]
googletest = { workspace = true }
tempfile = { workspace = true }
